### PR TITLE
Modifications for implementing CSLD into atomate

### PR DESCRIPTION
**Pull request by rees-c**
Summary of Changes:
-Moved some functions from csld_main to common_main so that they can be accessed more easily
-Made csfit return the cross validation error
-Made the phonon_step function return the squared phonon frequencies

### CODE REVIEW

**Review by feifzhou — COMMENTED** [review]
Only common tasks are to be put  into common_main.py, which is shared by not only CSLD specific routines (e.g. phonons), but also other models such as cluster expansion (CE), etc. A lattice-dynamics specific routines like phonons belong to their specific script (ce_main.py, under development).

I approve the othero change to returning errors

**Review by feifzhou — COMMENTED** [review]
I don't think it makes sense to return the eigen values in phonon_step in general, as this subroutine may do a bunch of different things depending on the settings. If wave vectors are not given, then the phonon frequencies are not even defined.

**Comment by feifzhou** [comment]
See my latest commit.

**Comment by rees-c** [comment]
Hello!

I am an intern in Anubhav Jain's group working on implementing a workflow into [atomate](https://github.com/hackingmaterials/atomate) for calculating lattice thermal conductivity using CSLD. As part of the workflow, we need to use several of the functions contained in csld_main (`SymmetrizedStructure`, `init_ld_model`, `fit_data`, `phonon_step`, `save_pot`, and `predict`). These functions are required to conduct the CSLD minimization (outputting the ShengBTE force constant files) and then check the quality of the solution by returning the cross-validation error and harmonic frequencies. Currently, these are all inside the csld_main script and are therefore not importable, even if csld is installed as a library. 

It seems the options are:
- Move these functions into the csld library and call them from within the csld_main script.
- Move the whole csld_main script into the csld library and make it an executable script using the entry_points functionality of setup-tools. For example: https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation
- Duplicate the full code of these functions in atomate so that we can replicate the behaviour of CSLD. 

Personally, we feel either the 1st or 2nd options would be the best choice, as these functions will be useful to anyone trying to use CSLD as a library. Also, if we duplicate this code, any updates you make to the csld_main scripts will not be reflected in atomate without us having to recopy the code. Whichever option you feel is most appropriate, we would be willing to implement the changes and submit another pull request. Do you have any thoughts on this?

Lastly in regards to eigE, we would like to be able to see whether CSLD is returning imaginary modes or not. If we added a boolean argument called `return_eigen` to `phonon_step` that returns eigenvalues if both `wavevector` is in `entries` and `return_eigen=True`, would this be ok? If not, what do you think would be the best way to proceed?

I am linking a postdoc in the Jain group at LBL who is also working on this project. @utf

**Comment by feifzhou** [comment]
1 sounds good. Give it a try

**Pull request closed without merging**
